server:
  port: 8080

spring:
  application:
    name: lumina-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: ${NACOS_GROUP:LUMINA_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: ${NACOS_GROUP:LUMINA_GROUP}
        file-extension: yaml

  config:
    import: optional:nacos:lumina-gateway.yaml
