package io.lumina.framework.web;

import io.lumina.common.core.BaseContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.MDC;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * LogContextInterceptor 单元测试
 *
 * <p>覆盖 traceId 从 Header 读取、自动生成、MDC 注入/清理、BaseContext 关联。
 *
 * @author Lumina Team
 * @since 2.0.0
 */
class LogContextInterceptorTest {

    private LogContextInterceptor interceptor;

    @BeforeEach
    void setUp() {
        interceptor = new LogContextInterceptor();
        MDC.clear();
    }

    @AfterEach
    void tearDown() {
        BaseContext.clear();
        MDC.clear();
    }

    @Test
    void traceIdFromHeaderInjectedToMdc() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("X-Trace-Id", "abc123trace");
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());

        assertThat(MDC.get(LogContextInterceptor.TRACE_ID)).isEqualTo("abc123trace");
        assertThat(response.getHeader("X-Trace-Id")).isEqualTo("abc123trace");
    }

    @Test
    void traceIdAutoGeneratedWhenMissing() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());

        String traceId = MDC.get(LogContextInterceptor.TRACE_ID);
        assertThat(traceId).isNotNull();
        assertThat(traceId).hasSize(32);
        assertThat(traceId).doesNotContain("-");
        assertThat(response.getHeader("X-Trace-Id")).isEqualTo(traceId);
    }

    @Test
    void emptyTraceIdHeaderTriggersAutoGen() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("X-Trace-Id", "");
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());

        String traceId = MDC.get(LogContextInterceptor.TRACE_ID);
        assertThat(traceId).isNotNull();
        assertThat(traceId).hasSize(32);
    }

    @Test
    void baseContextTenantIdInjectedToMdc() {
        BaseContext.setTenantId(42L);
        BaseContext.setUserId(100L);
        BaseContext.setUsername("alice");

        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());

        assertThat(MDC.get(LogContextInterceptor.TENANT_ID)).isEqualTo("42");
        assertThat(MDC.get(LogContextInterceptor.USER_ID)).isEqualTo("100");
        assertThat(MDC.get(LogContextInterceptor.USERNAME)).isEqualTo("alice");
    }

    @Test
    void nullBaseContextFieldsNotInMdc() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());

        assertThat(MDC.get(LogContextInterceptor.TENANT_ID)).isNull();
        assertThat(MDC.get(LogContextInterceptor.USER_ID)).isNull();
        assertThat(MDC.get(LogContextInterceptor.USERNAME)).isNull();
    }

    @Test
    void preHandleReturnsAlwaysTrue() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        boolean result = interceptor.preHandle(request, response, new Object());
        assertThat(result).isTrue();
    }

    @Test
    void afterCompletionClearsMdc() {
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("X-Trace-Id", "trace-to-clear");
        MockHttpServletResponse response = new MockHttpServletResponse();

        interceptor.preHandle(request, response, new Object());
        assertThat(MDC.get(LogContextInterceptor.TRACE_ID)).isNotNull();

        interceptor.afterCompletion(request, response, new Object(), null);

        assertThat(MDC.get(LogContextInterceptor.TRACE_ID)).isNull();
    }
}
