apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumina.fullname" . }}-secret
  labels:
    {{- include "lumina.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  RAG_EMBEDDING_API_KEY: {{ .Values.secrets.ragEmbeddingApiKey | quote }}
