spring:
  datasource:
    druid:
      password: 123456

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
    import-check:
      enabled: false
