server:
  port: 8081

spring:
  application:
    name: lumina-agent-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: ${NACOS_GROUP:LUMINA_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: ${NACOS_GROUP:LUMINA_GROUP}
        file-extension: yaml

  config:
    import: optional:nacos:lumina-agent-service.yaml
